engines:
  checkstyle:
    enabled: true
    channel: "beta"
  duplication:
    enabled: true
    config:
      - javascript:
  csslint:
    enabled: true

exclude_paths:
  - "**/node_modules/**/*"
  - "CalOrdersJET/bower_components/**/*"
  - "CalOrdersJET/src/js/libs/**/*"
  - "libs/**/*"
