
-- IMAGE CODES



INSERT INTO `calordersdb`.`PRD_IMG_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PDF',
'PDF',
'application/pdf',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`PRD_IMG_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('JPEG',
'jpeg',
'image/jpeg',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`PRD_IMG_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PNG',
'png',
'image/png',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
 
 
 

 -- PRD_CATEGORY_CD
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DHST','Desktop - Hardware - Standard','Desktop - Hardware - Standard','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DHPO','Desktop - Hardware - Power','Desktop - Hardware - Power','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DHWO','Desktop - Hardware - Workstation','Desktop - Hardware - Workstation','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DHTH','Desktop - Hardware - Thin Client','Desktop - Hardware - Thin Client','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DHAL','Desktop - Hardware - All in One','Desktop - Hardware - All in One','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DUST','Desktop - Upgrades - Standard ','Desktop - Upgrades - Standard ','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DUPO','Desktop - Upgrades - Power','Desktop - Upgrades - Power','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DUWO','Desktop - Upgrades - Workstation','Desktop - Upgrades - Workstation','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DUTH','Desktop - Upgrades - Thin Client','Desktop - Upgrades - Thin Client','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DUAL','Desktop - Upgrades - All in One','Desktop - Upgrades - All in One','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DUMO','Desktop - Upgrades - Monitor','Desktop - Upgrades - Monitor','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DMMO','Desktop - Monitors - Monitor','Desktop - Monitors - Monitor','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DSPO','Desktop - Service Upgrades - Power','Desktop - Service Upgrades - Power','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DSST','Desktop - Service Upgrades - Standard','Desktop - Service Upgrades - Standard','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DSMO','Desktop - Service Upgrades - Monitor','Desktop - Service Upgrades - Monitor','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DSWO','Desktop - Service Upgrades - Workstation','Desktop - Service Upgrades - Workstation','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DSTH','Desktop - Service Upgrades - Thin Client','Desktop - Service Upgrades - Thin Client','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DSAL','Desktop - Service Upgrades - All in One','Desktop - Service Upgrades - All in One','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DAAL','Desktop - Stand Alone Service','Desktop - Stand Alone Service','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LHST','Laptop - Hardware - Standard','Laptop - Hardware - Standard','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LHPO','Laptop - Hardware - Power','Laptop - Hardware - Power','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LHUL','Laptop - Hardware - Ultralight','Laptop - Hardware - Ultralight','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LHMO','Laptop - Hardware - Mobile','Laptop - Hardware - Mobile','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LUMO','Laptop - Upgrades - Mobile','Laptop - Upgrades - Mobile','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LUAL','Laptop - Upgrades - All','Laptop - Upgrades - All','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LUST','Laptop - Upgrades - Standard','Laptop - Upgrades - Standard','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LUPO','Laptop - Upgrades - Power','Laptop - Upgrades - Power','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LUUL','Laptop - Upgrades - Ultralight','Laptop - Upgrades - Ultralight','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LSMO','Laptop - Service Upgrades - Mobile','Laptop - Service Upgrades - Mobile','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LSPO','Laptop - Service Upgrades - Power','Laptop - Service Upgrades - Power','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LSUL','Laptop - Service Upgrades - Ultralight','Laptop - Service Upgrades - Ultralight','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LSST','Laptop - Service Upgrades - Standard','Laptop - Service Upgrades - Standard','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LSAL','Laptop - Service Upgrades - All','Laptop - Service Upgrades - All','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('LAAL','Laptop - Stand Alone Service','Laptop - Stand Alone Service','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`(`CODE`,`SHORT_DESC`,`LONG_DESC`,`CREATE_USER_ID`,`CREATE_TS`,`UPDATE_USER_ID`,`UPDATE_TS`)VALUES('DUOT','Desktop - Upgrades - Other','Desktop - Upgrades - Other','system',CURRENT_TIMESTAMP,'system',CURRENT_TIMESTAMP);

INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OPSY',
'Operating Systems',
'Operating Systems',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SECC',
'Security',
'Security Products',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('UTIL',
'Utilities',
'Utility Software',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SERI',
'Independent Services',
'Independent Services',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);

INSERT INTO `calordersdb`.`PRD_CATEGORY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OFFC',
'Office Software',
'Office Software',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


-- ORD_STATUS_CD

INSERT INTO `calordersdb`.`ORD_STATUS_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SUBT',
'Submitted',
'Order has been submitted',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`ORD_STATUS_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PRCS',
'Processing',
'Order is being processed.',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`ORD_STATUS_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SHIP',
'Shipped',
'Order has been shipped',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`ORD_STATUS_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CANC',
'Cancelled',
'Order has been Cancelled',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



-- EMC_TYPE_CD INSERTS
INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HPH',
'Home Phone',
'Home Phone',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WPH',
'Work Phone',
'Work Phone',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MPH',
'Mobile Phone',
'Mobile Phone',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PEM',
'Personal Email',
'Personal Email Address',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WEM',
'Work Email',
'Work Email Address',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TWI',
'Twitter Address',
'Twitter Address',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FAC',
'FaceBook Address',
'FaceBook Address',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



INSERT INTO `calordersdb`.`EMC_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LIN',
'LinkedIn Address',
'LinkedIn Address',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);









-- COUNTRY INSERTS


INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AFG',
'4',
'Afghanistan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ALA',
'248',
'Aland Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ALB',
'8',
'Albania',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DZA',
'12',
'Algeria',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ASM',
'16',
'American Samoa',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AND',
'20',
'Andorra',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AGO',
'24',
'Angola',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AIA',
'660',
'Anguilla',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ATA',
'10',
'Antarctica',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ATG',
'28',
'Antigua and Barbuda',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ARG',
'32',
'Argentina',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ARM',
'51',
'Armenia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ABW',
'533',
'Aruba',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AUS',
'36',
'Australia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AUT',
'40',
'Austria',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AZE',
'31',
'Azerbaijan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BHS',
'44',
'Bahamas',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BHR',
'48',
'Bahrain',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BGD',
'50',
'Bangladesh',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BRB',
'52',
'Barbados',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BLR',
'112',
'Belarus',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BEL',
'56',
'Belgium',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BLZ',
'84',
'Belize',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BEN',
'204',
'Benin',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BMU',
'60',
'Bermuda',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BTN',
'64',
'Bhutan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BOL',
'68',
'Bolivia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BIH',
'70',
'Bosnia and Herzegovina',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BWA',
'72',
'Botswana',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BVT',
'74',
'Bouvet Island',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BRA',
'76',
'Brazil',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VGB',
'92',
'British Virgin Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IOT',
'86',
'British Indian Ocean Territory',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BRN',
'96',
'Brunei Darussalam',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BGR',
'100',
'Bulgaria',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BFA',
'854',
'Burkina Faso',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BDI',
'108',
'Burundi',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KHM',
'116',
'Cambodia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CMR',
'120',
'Cameroon',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CAN',
'124',
'Canada',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CPV',
'132',
'Cape Verde',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CYM',
'136',
'Cayman Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CAF',
'140',
'Central African Republic',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TCD',
'148',
'Chad',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CHL',
'152',
'Chile',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CHN',
'156',
'China',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HKG',
'344',
'Hong Kong Special Administrative Region of China',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MAC',
'446',
'Macao Special Administrative Region of China',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CXR',
'162',
'Christmas Island',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CCK',
'166',
'Cocos (Keeling) Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('COL',
'170',
'Colombia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('COM',
'174',
'Comoros',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('COG',
'178',
'Congo (Brazzaville)',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('COD',
'180',
'Congo Democratic Republic of the',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('COK',
'184',
'Cook Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CRI',
'188',
'Costa Rica',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CIV',
'384',
'Cote dIvoire',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HRV',
'191',
'Croatia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CUB',
'192',
'Cuba',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CYP',
'196',
'Cyprus',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CZE',
'203',
'Czech Republic',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DNK',
'208',
'Denmark',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DJI',
'262',
'Djibouti',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DMA',
'212',
'Dominica',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DOM',
'214',
'Dominican Republic',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ECU',
'218',
'Ecuador',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('EGY',
'818',
'Egypt',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SLV',
'222',
'El Salvador',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GNQ',
'226',
'Equatorial Guinea',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ERI',
'232',
'Eritrea',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('EST',
'233',
'Estonia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ETH',
'231',
'Ethiopia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FLK',
'238',
'Falkland Islands (Malvinas)',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FRO',
'234',
'Faroe Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FJI',
'242',
'Fiji',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FIN',
'246',
'Finland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FRA',
'250',
'France',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GUF',
'254',
'French Guiana',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PYF',
'258',
'French Polynesia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ATF',
'260',
'French Southern Territories',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GAB',
'266',
'Gabon',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GMB',
'270',
'Gambia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GEO',
'268',
'Georgia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DEU',
'276',
'Germany',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GHA',
'288',
'Ghana',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GIB',
'292',
'Gibraltar',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GRC',
'300',
'Greece',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GRL',
'304',
'Greenland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GRD',
'308',
'Grenada',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GLP',
'312',
'Guadeloupe',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GUM',
'316',
'Guam',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GTM',
'320',
'Guatemala',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GGY',
'831',
'Guernsey',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GIN',
'324',
'Guinea',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GNB',
'624',
'Guinea-Bissau',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GUY',
'328',
'Guyana',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HTI',
'332',
'Haiti',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HMD',
'334',
'Heard Island and Mcdonald Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VAT',
'336',
'Holy See (Vatican City State)',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HND',
'340',
'Honduras',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HUN',
'348',
'Hungary',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ISL',
'352',
'Iceland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IND',
'356',
'India',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IDN',
'360',
'Indonesia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IRN',
'364',
'Iran Islamic Republic of',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IRQ',
'368',
'Iraq',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IRL',
'372',
'Ireland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IMN',
'833',
'Isle of Man',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ISR',
'376',
'Israel',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ITA',
'380',
'Italy',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('JAM',
'388',
'Jamaica',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('JPN',
'392',
'Japan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('JEY',
'832',
'Jersey',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('JOR',
'400',
'Jordan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KAZ',
'398',
'Kazakhstan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KEN',
'404',
'Kenya',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KIR',
'296',
'Kiribati',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PRK',
'408',
'Korea Democratic Peoples Republic of',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KOR',
'410',
'Korea Republic of',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KWT',
'414',
'Kuwait',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KGZ',
'417',
'Kyrgyzstan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LAO',
'418',
'Lao PDR',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LVA',
'428',
'Latvia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LBN',
'422',
'Lebanon',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LSO',
'426',
'Lesotho',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LBR',
'430',
'Liberia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LBY',
'434',
'Libya',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LIE',
'438',
'Liechtenstein',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LTU',
'440',
'Lithuania',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LUX',
'442',
'Luxembourg',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MKD',
'807',
'Macedonia Republic of',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MDG',
'450',
'Madagascar',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MWI',
'454',
'Malawi',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MYS',
'458',
'Malaysia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MDV',
'462',
'Maldives',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MLI',
'466',
'Mali',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MLT',
'470',
'Malta',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MHL',
'584',
'Marshall Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MTQ',
'474',
'Martinique',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MRT',
'478',
'Mauritania',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MUS',
'480',
'Mauritius',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MYT',
'175',
'Mayotte',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MEX',
'484',
'Mexico',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FSM',
'583',
'Micronesia Federated States of',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MDA',
'498',
'Moldova',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MCO',
'492',
'Monaco',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MNG',
'496',
'Mongolia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MNE',
'499',
'Montenegro',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MSR',
'500',
'Montserrat',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MAR',
'504',
'Morocco',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MOZ',
'508',
'Mozambique',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MMR',
'104',
'Myanmar',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NAM',
'516',
'Namibia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NRU',
'520',
'Nauru',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NPL',
'524',
'Nepal',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NLD',
'528',
'Netherlands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ANT',
'530',
'Netherlands Antilles',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NCL',
'540',
'New Caledonia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NZL',
'554',
'New Zealand',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NIC',
'558',
'Nicaragua',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NER',
'562',
'Niger',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NGA',
'566',
'Nigeria',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NIU',
'570',
'Niue',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NFK',
'574',
'Norfolk Island',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MNP',
'580',
'Northern Mariana Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NOR',
'578',
'Norway',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OMN',
'512',
'Oman',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PAK',
'586',
'Pakistan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PLW',
'585',
'Palau',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PSE',
'275',
'Palestinian Territory Occupied',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PAN',
'591',
'Panama',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PNG',
'598',
'Papua New Guinea',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PRY',
'600',
'Paraguay',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PER',
'604',
'Peru',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PHL',
'608',
'Philippines',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PCN',
'612',
'Pitcairn',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('POL',
'616',
'Poland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PRT',
'620',
'Portugal',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PRI',
'630',
'Puerto Rico',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('QAT',
'634',
'Qatar',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('REU',
'638',
'Réunion',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ROU',
'642',
'Romania',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('RUS',
'643',
'Russian Federation',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('RWA',
'646',
'Rwanda',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('BLM',
'652',
'Saint-Barthélemy',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SHN',
'654',
'Saint Helena',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KNA',
'659',
'Saint Kitts and Nevis',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LCA',
'662',
'Saint Lucia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MAF',
'663',
'Saint-Martin (French part)',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SPM',
'666',
'Saint Pierre and Miquelon',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VCT',
'670',
'Saint Vincent and Grenadines',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WSM',
'882',
'Samoa',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SMR',
'674',
'San Marino',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('STP',
'678',
'Sao Tome and Principe',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SAU',
'682',
'Saudi Arabia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SEN',
'686',
'Senegal',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SRB',
'688',
'Serbia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SYC',
'690',
'Seychelles',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SLE',
'694',
'Sierra Leone',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SGP',
'702',
'Singapore',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SVK',
'703',
'Slovakia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SVN',
'705',
'Slovenia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SLB',
'90',
'Solomon Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SOM',
'706',
'Somalia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ZAF',
'710',
'South Africa',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SGS',
'239',
'South Georgia and the South Sandwich Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SSD',
'728',
'South Sudan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ESP',
'724',
'Spain',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LKA',
'144',
'Sri Lanka',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SDN',
'736',
'Sudan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SUR',
'740',
'Suriname *',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SJM',
'744',
'Svalbard and Jan Mayen Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SWZ',
'748',
'Swaziland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SWE',
'752',
'Sweden',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CHE',
'756',
'Switzerland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SYR',
'760',
'Syrian Arab Republic (Syria)',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TWN',
'158',
'Taiwan Republic of China',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TJK',
'762',
'Tajikistan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TZA',
'834',
'Tanzania United Republic of',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('THA',
'764',
'Thailand',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TLS',
'626',
'Timor-Leste',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TGO',
'768',
'Togo',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TKL',
'772',
'Tokelau',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TON',
'776',
'Tonga',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TTO',
'780',
'Trinidad and Tobago',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TUN',
'788',
'Tunisia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TUR',
'792',
'Turkey',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TKM',
'795',
'Turkmenistan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TCA',
'796',
'Turks and Caicos Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TUV',
'798',
'Tuvalu',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('UGA',
'800',
'Uganda',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('UKR',
'804',
'Ukraine',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ARE',
'784',
'United Arab Emirates',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GBR',
'826',
'United Kingdom',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('USA',
'840',
'United States of America',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('UMI',
'581',
'United States Minor Outlying Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('URY',
'858',
'Uruguay',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('UZB',
'860',
'Uzbekistan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VUT',
'548',
'Vanuatu',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VEN',
'862',
'Venezuela (Bolivarian Republic of)',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VNM',
'704',
'Viet Nam',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VIR',
'850',
'Virgin Islands US',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WLF',
'876',
'Wallis and Futuna Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ESH',
'732',
'Western Sahara',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('YEM',
'887',
'Yemen',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ZMB',
'894',
'Zambia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_COUNTRY_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ZWE',
'716',
'Zimbabwe',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);





-- STATE INSERTS

INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AL',
'1',
' Alabama',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AK',
'2',
' Alaska',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AZ',
'4',
' Arizona',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AR',
'5',
' Arkansas',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CA',
'6',
' California',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CO',
'8',
' Colorado',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('CT',
'9',
' Connecticut',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DE',
'10',
' Delaware',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('DC',
'11',
' District of Columbia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('FL',
'12',
' Florida',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GA',
'13',
' Georgia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HI',
'15',
' Hawaii',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ID',
'16',
' Idaho',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IL',
'17',
' Illinois',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IN',
'18',
' Indiana',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('IA',
'19',
' Iowa',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KS',
'20',
' Kansas',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('KY',
'21',
' Kentucky',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('LA',
'22',
' Louisiana',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ME',
'23',
' Maine',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MD',
'24',
' Maryland',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MA',
'25',
' Massachusetts',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MI',
'26',
' Michigan',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MN',
'27',
' Minnesota',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MS',
'28',
' Mississippi',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MO',
'29',
' Missouri',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MT',
'30',
' Montana',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NE',
'31',
' Nebraska',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NV',
'32',
' Nevada',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NH',
'33',
' New Hampshire',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NJ',
'34',
' New Jersey',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NM',
'35',
' New Mexico',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NY',
'36',
' New York',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('NC',
'37',
' North Carolina',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ND',
'38',
' North Dakota',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OH',
'39',
' Ohio',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OK',
'40',
' Oklahoma',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('OR',
'41',
' Oregon',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PA',
'42',
' Pennsylvania',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('RI',
'44',
' Rhode Island',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SC',
'45',
' South Carolina',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('SD',
'46',
' South Dakota',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TN',
'47',
' Tennessee',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('TX',
'48',
' Texas',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('UT',
'49',
' Utah',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VT',
'50',
' Vermont',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VA',
'51',
' Virginia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WA',
'53',
' Washington',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WV',
'54',
' West Virginia',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WI',
'55',
' Wisconsin',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('WY',
'56',
' Wyoming',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AS',
'60',
' American Samoa',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('GU',
'66',
' Guam',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('MP',
'69',
' Northern Mariana Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('PR',
'72',
' Puerto Rico',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);
INSERT INTO `calordersdb`.`ADR_STATE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('VI',
'78',
' U.S. Virgin Islands',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



 
INSERT INTO `calordersdb`.`GRP_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('AAD',
'Account Administrator',
'Account Administrator',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);

INSERT INTO `calordersdb`.`GRP_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('ADM',
'Administrator',
'Administrator',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);

INSERT INTO `calordersdb`.`GRP_TYPE_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('EMP',
'Employee',
'Employee',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);



-- PRD_UNIT_CD

INSERT INTO `calordersdb`.`PRD_UNIT_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('EACH',
'Each',
'Each',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);


INSERT INTO `calordersdb`.`PRD_UNIT_CD`
(`CODE`,
`SHORT_DESC`,
`LONG_DESC`,
`CREATE_USER_ID`,
`CREATE_TS`,
`UPDATE_USER_ID`,
`UPDATE_TS`)
VALUES
('HOUR',
'Hour',
'Hour',
'system',
CURRENT_TIMESTAMP,
'system',
CURRENT_TIMESTAMP);

